orbs:
  react: "thefrontside/react@0.2.0"

version: 2.1
jobs:
  deploy:
    filters: 
      branches:
        only: master
    steps:
      - react/install
      - react/eslint:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install
      - react/coverage:
          requires:
            - react/install

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - deploy
