orbs:
  react: "thefrontside/react@0.2.0"

aliases:
 - &filter-only-master
    branches:
      only:
        - master

version: 2.1
jobs:
  deploy:
    steps:
      - react/install
          filters: 
            branches: 
              *filter-only-master
      - react/eslint:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install
      - react/coverage:
          requires:
            - react/install

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - deploy
